### ISSUE TITLE
Update to 2.78

### ISSUE THREAD

**Issue by justicel** [4km3/docker-dnsmasq#12]
There is a critical vulnerability in dnsmasq. Can you update your image to 2.78 to fix it? Thanks!!

**Comment by olegstepura** [comment]
Here are the details:
https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html

DNSMasq merged the patches:
http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=summary
![2017-10-03 09_26_37-thekelleys org uk git - dnsmasq git_summary](https://user-images.githubusercontent.com/534510/31114157-fec8dc26-a81c-11e7-8e7f-6438a6a52a6a.png)

https://github.com/google/security-research-pocs/tree/master/vulnerabilities/dnsmasq

**Comment by olegstepura** [comment]
Seems lile the only way to use `2.78` is to use `Alpine edge`. https://pkgs.alpinelinux.org/package/edge/main/x86/dnsmasq

**Comment by andyshinn** [comment]
There is a 2.78 tag now.
