### ISSUE TITLE
inotifywait dnsmasq.conf althosts -> HUP

### ISSUE THREAD

**Issue by ReSearchITEng** [4km3/docker-dnsmasq#15]
Any plans to use inotifywait to monitor the changes on files like  dnsmasq.conf and althosts and send HUP signal ?

Similar to: this other image: https://github.com/aciobanu/docker-dnsmasq/blob/master/entrypoint.sh ?

**Comment by andyshinn** [comment]
Unfortunately, no. This image is designed to be used as a base. As such, it will be as minimal as possible with no custom scripts. If you want to do that, I would just build an image off this base or use that image if it does what you are after.
