### ISSUE TITLE
Feature: Multiple architectures using manifest

### ISSUE THREAD

**Issue by mapero** [4km3/docker-dnsmasq#16]
Hi,
may it be possible to make this image support multiple architectures(e.g. armv7) using a manifest list?
https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

Thanks.

Best regards,
Jochen

**Comment by andyshinn** [comment]
No. It is unlikely I'll be able to do that until Docker supports building multiple architectures for their automated builds on Docker Hub.

**Comment by andyshinn** [comment]
It looks like this is supported now via hooks: https://docs.docker.com/docker-hub/builds/advanced/. But I don't have time to set it up. If someone wants to open a PR I can review.

**Comment by ocean** [comment]
@panchoh Hi there, I've been using the andyshinn version of this image for a couple of years. I recently switched to an Apple M1 MBP and so have rebuilt this image for `linux/arm64` for my own use (and others are using it now too).

I have multi-arch image builds running on my local machine, and via GitHub Actions as well. I forked your repo and tried to get multi-arch "autobuilds" running on Docker Hub infrastructure using custom `pre_build` and `build` hooks, but it seems they don't work yet as the infrastructure is running on Ubuntu 16.04 which doesn't have a recent enough kernel to support the buildkit QEMU emulation required. I'm going to ask the Docker people when their infrastructure images are likely to be updated.

Would you be interested in a PR from me adding GitHub Actions-based multi-arch image builds to this repo?

**Comment by panchoh** [comment]
> @panchoh Hi there, I've been using the andyshinn version of this image for a couple of years. I recently switched to an Apple M1 MBP and so have rebuilt this image for `linux/arm64` for my own use (and others are using it now too).
> 
> I have multi-arch image builds running on my local machine, and via GitHub Actions as well. I forked your repo and tried to get multi-arch "autobuilds" running on Docker Hub infrastructure using custom `pre_build` and `build` hooks, but it seems they don't work yet as the infrastructure is running on Ubuntu 16.04 which doesn't have a recent enough kernel to support the buildkit QEMU emulation required. I'm going to ask the Docker people when their infrastructure images are likely to be updated.
> 
> Would you be interested in a PR from me adding GitHub Actions-based multi-arch image builds to this repo?

Hi, @ocean! Sorry, I completely missed your comment until now :-(

We've implemented multi-arch support leveraging the official Docker GitHub Actions, which makes it super-easy to produce them.
Thanks for the offer to help, and sorry for not reading it and replying to you in a timely fashion.

Happy hacking,

**Comment by ocean** [comment]
Hi @panchoh , no worries, I'm glad you've added the multi-arch with GitHub Actions now, good stuff 😄

**Comment by panchoh** [comment]
> Hi @panchoh , no worries, I'm glad you've added the multi-arch with GitHub Actions now, good stuff

Thanks, @ocean !
