### ISSUE TITLE
provide updated images on dockerhub

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [4km3/docker-dnsmasq#23]
The last image on dockerhub is 9 month old. Several new released versions are published in the meantime. To be able to use this image directly, instead of building locally an automated build and update job for the dockerhub images would be beneficial.

best,
Christian

**Comment by andyshinn** [comment]
I've pushed new releases up to current Alpine as of now (Alpine 3.12 and dnsmasq 2.81).
