### ISSUE TITLE
dnsmasq is out of date

### ISSUE THREAD

**Issue by pouyanh** [4km3/docker-dnsmasq#3]
Hi;
  The dockerized dnsmasq is old (2.72) so it doesn' support the 'hostsdir' config parameter. I need to have a shared directory (and not a file cause one file is locked but dir is not) like config-dir but re-readable on SIGHUP and that is 'hostsdir' or 'dhcp-hostsdir' which are both added after 2.72

  Please update the dnsmasq binary to support this feature. I need it to use dnsmasq following docker-gen

**Comment by andyshinn** [comment]
Alpine 3.3 will be released in the next week or two which contains dnsmasq 2.75. I will bump this image to Alpine 3.3 and dnsmasq 2.75 when it is released.

**Comment by andyshinn** [comment]
I pushed version 2.75 which is based on Alpine 3.3.
