### ISSUE TITLE
Up for adoption

### ISSUE THREAD

**Issue by andyshinn** [4km3/docker-dnsmasq#32]
Please respond if you would like to adopt this repository. I would transfer to you and help facilitate the handoff of the Docker Hub account. Would prefer if you have prior Docker and Docker image management experience.

**Comment by rodrigofuente** [comment]
Hello, @andyshinn.
Big fan here!  I would love to adopt this project and keep it alive and kicking.
I share an organization ([4km3](https://github.com/4km3)) with @panchoh, so we would host it there.

We would be up to having a virtual meeting if you want to know more about us.

At any rate, thanks a bunch for maintaining this one all these years!

**Comment by panchoh** [comment]
Aye, we would be honored!

**Comment by andyshinn** [comment]
Great, I will check it out soon and get back to you with a plan in a week or two!

**Comment by aminvakil** [comment]
I can maintain this too if you want, although I have migrated all my docker images to quay.io because of docker hub limits.

**Comment by mihai-stancu** [comment]
Has this transition happened? @rodrigofuente

**Comment by rodrigofuente** [comment]
Hello @mihai-stancu, not as of yet. Any update on the plans @andyshinn?

**Comment by andyshinn** [comment]
@rodrigofuente it looks like you will need to remove the repository already on the organization before I can initiate the transfer.

**Comment by rodrigofuente** [comment]
Repository at 4km3 organization deleted

**Comment by andyshinn** [comment]
It now says:

> You don’t have the permission to create public repositories on 4km3

**Comment by panchoh** [comment]
Hi, @andyshinn!

We've created an interim [GitHub org](https://github.com/4km3-incoming) for performing the transition. We'll invite you shortly. If you choose to accept, Mr. Hunt,  you can transfer the repo afterwards.

Cheers!

**Comment by panchoh** [comment]
Hi again, @andyshinn.

The repo has been successfully transferred to 4km3, yay!

Do you have any suggestions for handling the docker hub side of the "transfer"?

TIA.

**Comment by andyshinn** [comment]
I updated the readme to say it is moved to https://hub.docker.com/repository/docker/4km3/dnsmasq/general. You'll need to create the new Docker Hub repo. It doesn't appear there is a way to transfer.

**Comment by panchoh** [comment]
> I updated the readme to say it is moved to https://hub.docker.com/repository/docker/4km3/dnsmasq/general.

Thanks for that.

> You'll need to create the new Docker Hub repo.

Done.

> It doesn't appear there is a way to transfer.
We concur.  Bad, docker hub, baaad.

We'll take it from here.  Thanks, @andyshinn.
