### ISSUE TITLE
Log to stdout/stderr

### ISSUE THREAD

**Issue by strarsis** [4km3/docker-dnsmasq#5]
It would be helpful when dnsmasq is configured by default to log to stdout/stderr 
so one can attach docker log to it to see the logs.
Currently I get no logs at all when I attach to it with docker logs.

**Comment by andyshinn** [comment]
You can log to stdout using `--log-facility=-`. I'll update the README to reflect this.

**Comment by jwulf** [comment]
Where do I put that command, because `docker run` tells me that it doesn't recognise it...

**Comment by strarsis** [comment]
@jwulf: You would append `--log-facility=-` (there is a minus ('-') at the end) as argument, 
adjusted example command from README:
````
$ docker run -p 53:53/tcp -p 53:53/udp --cap-add=NET_ADMIN andyshinn/dnsmasq:2.75 -S /consul/10.17.0.2 --log-facility=-
````
